
export const galleryImages = {
  "Hair Transplant": [
    "/gallery/hair_trans_img_1.png",
    "/gallery/hair_trans_img_2.png",
    "/gallery/hair_trans_img_3.png",
    "/gallery/hair_trans_img_4.png",
    "/gallery/hair_trans_img_5.png",
    "/gallery/hair_trans_img_6.png",
    "/gallery/hair_trans_img_4.png",
    "/gallery/hair_trans_img_5.png",
    "/gallery/hair_trans_img_6.png",
    "/gallery/hair_trans_img_1.png",
    "/gallery/hair_trans_img_2.png",
    "/gallery/hair_trans_img_3.png",
  ],
  "Body Contouring Abdominal Platy": [
    "/gallery/hair_trans_img_4.png",
    "/gallery/hair_trans_img_5.png",
    "/gallery/hair_trans_img_6.png",
    "/gallery/hair_trans_img_1.png",
    "/gallery/hair_trans_img_2.png",
    "/gallery/hair_trans_img_3.png",
    "/gallery/hair_trans_img_6.png",
    "/gallery/hair_trans_img_1.png",
    "/gallery/hair_trans_img_2.png",
    "/gallery/hair_trans_img_5.png",
    "/gallery/hair_trans_img_3.png",
    "/gallery/hair_trans_img_4.png",

  ],
  "Breast Augmentation/Breast Enhancement": [
    "/gallery/hair_trans_img_6.png",
    "/gallery/hair_trans_img_1.png",
    "/gallery/hair_trans_img_2.png",
    "/gallery/hair_trans_img_5.png",
    "/gallery/hair_trans_img_3.png",
    "/gallery/hair_trans_img_4.png",
  ],
};
